name: Continuous Delivery

on:
  workflow_run:
    workflows: ['Continuous Integration']
    types:
      - completed
    branches:
      - main

jobs:
  publish:
    name: Publish on Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker image build -t gabrielrufino/strabot-telegram:latest -t gabrielrufino/strabot-telegram:$(npm pkg get version | sed 's/"//g') .
      - name: Log in docker hub
        run: docker login -u gabrielrufino -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Publish image
        run: docker image push -a gabrielrufino/strabot-telegram
      - name: Set docker hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: gabrielrufino
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: gabrielrufino/strabot-telegram
