name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  tests:
    strategy:
      matrix:
        node-version: [12, 14, 16, 18]
        os: [ubuntu-latest] # Add other systems

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npm run lint

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
