name: CI

on:
  - push

jobs:
  tests:
    strategy:
      matrix:
        node-version: [12, 14, 16, 18]
        os: [ubuntu-latest] # Add other systems

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
